const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const context={window:{}, console};
context.window=context;
vm.createContext(context);
for(const file of ['js/activity-model.js','js/activity-detail-model.js','js/post-run-review.js']) vm.runInContext(fs.readFileSync(file,'utf8'),context);
context.formatPace=n=>`${Math.floor(n)}:${String(Math.round(n%1*60)).padStart(2,'0')}`;
const detail={source:'coros',sourceId:'one',laps:[{index:1,distanceKm:1,durationMin:6.3716667,pace:6.3716667,averageHr:122,cadence:175},{index:2,distanceKm:.03,durationMin:13.28/60,pace:13.28/60/.03}],coverage:{laps:true,map:false,streams:false}};
const workout={_key:'hc1',date:'2026-09-08',type:'run',source:'health_connect',dist:1.03,time:6.6,corosDetail:detail};
assert.equal(context.MyDashActivityAnalysis.detailFor(workout),detail);
assert.equal(Math.round(context.MyDashActivityAnalysis.analyze(workout).averageCadence),175);
const html=context.postRunHealthConnectLaps(workout);
assert.match(html,/COROS/); assert.match(html,/6:22/); assert.match(html,/0.03 km/); assert.match(html,/0:13/); assert.match(html,/175/);
assert.equal(context.sourceMeta(workout).label,'COROS');
context._workouts=[workout,{...workout,_key:'hc-old',corosDetail:undefined}];
context._stravaWorkouts=[];
assert.equal(context.getAllActivities().length,1);
assert.equal(context.getAllActivities()[0]._key,'hc1');
context._workouts=[workout,{...workout,_key:'hc2',corosDetail:{...detail,sourceId:'two'}}];
assert.equal(context.getAllActivities().length,2,'distinct COROS sessions must not collapse');
console.log('COROS activity rendering, remainder, provenance and dedupe checks passed');
