import {escape as e} from '../ui/format.mjs';
export function sheetsView(){return `<section class="card"><h2>สำรองไป Google Sheets</h2><p>ใช้ Apps Script เดิม ส่งกิจกรรมและสุขภาพเท่านั้น ไม่ใช่การซิงก์นาฬิกา</p><form id="sheets-settings"><label>Apps Script URL<input name="url" type="url" required autocomplete="off"></label><label>Token ใหม่ (เว้นว่างเพื่อเก็บค่าเดิม)<input name="token" type="password" autocomplete="new-password"></label><button class="button">บันทึกการตั้งค่า</button></form><p id="sheets-config-status" role="status"></p><p>เบราว์เซอร์อ่านคำตอบจาก Apps Script แบบ no-cors ไม่ได้ จะแสดงเพียง “ส่งคำขอแล้ว” คุณต้องตรวจ Activities / Daily_Wellness / System_Log ในชีตเอง ไม่ถือว่าสำรองสำเร็จเพียงเพราะส่งได้</p><button type="button" class="button" id="sheets-ping">ส่งคำขอทดสอบ</button> <button type="button" class="button" id="sheets-send">ส่งกิจกรรมและสุขภาพ</button><p id="sheets-send-status" role="status"></p><p class="muted">ต้องออนไลน์และเข้าสู่ระบบ ไม่มีการส่งอัตโนมัติหรือเก็บ token/ข้อมูลใน localStorage หากส่งขาดช่วง สามารถส่งซ้ำได้โดยปลายทางเดิมใช้ upsert</p></section>`;}
export function bindSheets({cloud,requireCloud,model,onBusy=()=>{}}){
  const form=document.querySelector('#sheets-settings');if(!form)return;
  const configStatus=document.querySelector('#sheets-config-status'),status=document.querySelector('#sheets-send-status');
  const busy=value=>{onBusy(value);document.querySelectorAll('#sheets-settings button,#sheets-ping,#sheets-send').forEach(button=>button.disabled=value);};
  form.addEventListener('input',()=>{form.dataset.dirty='true';});
  (async()=>{try{requireCloud();const cfg=await cloud().readSheetsSettings();if(!form.isConnected)return;form.elements.url.value=cfg.url;configStatus.textContent=cfg.hasToken?'มี token ที่บันทึกอยู่แล้ว (ไม่แสดงค่า)':'ยังไม่มี token';}catch{configStatus.textContent='เข้าสู่ระบบเพื่ออ่านและตั้งค่า Google Sheets';}})();
  form.onsubmit=async event=>{event.preventDefault();try{requireCloud();busy(true);await cloud().saveSheetsSettings({url:form.elements.url.value,token:form.elements.token.value});form.elements.token.value='';configStatus.textContent='บันทึกและอ่านกลับการตั้งค่าแล้ว';}catch(error){configStatus.textContent=error.message;}finally{busy(false);}};
  for(const [id,ping] of [['sheets-ping',true],['sheets-send',false]])document.getElementById(id).onclick=async()=>{
    try{requireCloud();if(!confirm(ping?'ส่งคำขอ ping ไป Apps Script ที่ตั้งค่าไว้?':'ส่งกิจกรรมและสุขภาพที่อ่านอยู่ไป Apps Script ที่ตั้งค่าไว้? กรุณาตรวจ URL ก่อนส่ง'))return;busy(true);status.textContent='กำลังส่งคำขอ…';const result=await cloud().backupSheets(model.data,ping,(sent,total)=>status.textContent=`ส่งคำขอแล้ว ${sent}/${total} (ยังยืนยันปลายทางไม่ได้)`);status.textContent=`ส่งคำขอแล้ว ${result.sent} รายการ — ยังยืนยันการบันทึกไม่ได้ กรุณาตรวจชีตปลายทาง`;}catch(error){status.textContent='หยุดส่ง: '+e(error.message)+' ตรวจชีตก่อนส่งซ้ำ';}finally{busy(false);}
  };
}
